// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Orchard.Fields.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Input Field")]
    public partial class InputFieldFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Input.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Input Field", "  In order to add an input to my types\r\nAs an administrator\r\n  I want to create, " +
                    "edit and publish input fields", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating and using Input fields")]
        public virtual void CreatingAndUsingInputFields()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating and using Input fields", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 9
    testRunner.Given("I have installed Orchard");
#line 10
  testRunner.And("I have installed \"Orchard.Fields\"");
#line 11
    testRunner.When("I go to \"Admin/ContentTypes\"");
#line 12
    testRunner.Then("I should see \"<a[^>]*>.*?Create new type</a>\"");
#line 13
    testRunner.When("I go to \"Admin/ContentTypes/Create\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table1.AddRow(new string[] {
                        "DisplayName",
                        "Event"});
            table1.AddRow(new string[] {
                        "Name",
                        "Event"});
#line 14
        testRunner.And("I fill in", ((string)(null)), table1);
#line 18
        testRunner.And("I hit \"Create\"");
#line 19
        testRunner.And("I go to \"Admin/ContentTypes/\"");
#line 20
    testRunner.Then("I should see \"Event\"");
#line 23
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line 24
  testRunner.And("I follow \"Add Field\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table2.AddRow(new string[] {
                        "DisplayName",
                        "Contact"});
            table2.AddRow(new string[] {
                        "Name",
                        "Contact"});
            table2.AddRow(new string[] {
                        "FieldTypeName",
                        "InputField"});
#line 25
  testRunner.And("I fill in", ((string)(null)), table2);
#line 30
  testRunner.And("I hit \"Save\"");
#line 31
  testRunner.And("I am redirected");
#line 32
 testRunner.Then("I should see \"The \\\"Contact\\\" field has been added.\"");
#line 35
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table3.AddRow(new string[] {
                        "Fields[0].InputFieldSettings.Hint",
                        "Enter the contact email address"});
#line 36
  testRunner.And("I fill in", ((string)(null)), table3);
#line 39
  testRunner.And("I hit \"Save\"");
#line 40
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line 41
 testRunner.Then("I should see \"Enter the contact email address\"");
#line 53
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table4.AddRow(new string[] {
                        "Fields[0].InputFieldSettings.Type",
                        "Email"});
#line 54
  testRunner.And("I fill in", ((string)(null)), table4);
#line 57
  testRunner.And("I hit \"Save\"");
#line 58
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line 59
 testRunner.Then("I should see \"type=\\\"email\\\"\"");
#line 62
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table5.AddRow(new string[] {
                        "Fields[0].InputFieldSettings.Title",
                        "Enter an email address"});
#line 63
  testRunner.And("I fill in", ((string)(null)), table5);
#line 66
  testRunner.And("I hit \"Save\"");
#line 67
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line 68
 testRunner.Then("I should see \"title=\\\"Enter an email address\\\"\"");
#line 71
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table6.AddRow(new string[] {
                        "Fields[0].InputFieldSettings.AutoFocus",
                        "true"});
#line 72
  testRunner.And("I fill in", ((string)(null)), table6);
#line 75
  testRunner.And("I hit \"Save\"");
#line 76
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line 77
 testRunner.Then("I should see \"autofocus=\\\"autofocus\\\"\"");
#line 80
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table7.AddRow(new string[] {
                        "Fields[0].InputFieldSettings.AutoComplete",
                        "true"});
#line 81
  testRunner.And("I fill in", ((string)(null)), table7);
#line 84
  testRunner.And("I hit \"Save\"");
#line 85
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line 86
 testRunner.Then("I should see \"autocomplete=\\\"on\\\"\"");
#line 89
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table8.AddRow(new string[] {
                        "Fields[0].InputFieldSettings.Placeholder",
                        "email@domain.com"});
#line 90
  testRunner.And("I fill in", ((string)(null)), table8);
#line 93
  testRunner.And("I hit \"Save\"");
#line 94
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line 95
 testRunner.Then("I should see \"placeholder=\\\"email@domain.com\\\"\"");
#line 98
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table9.AddRow(new string[] {
                        "Fields[0].InputFieldSettings.MaxLength",
                        "100"});
#line 99
  testRunner.And("I fill in", ((string)(null)), table9);
#line 102
  testRunner.And("I hit \"Save\"");
#line 103
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line 104
 testRunner.Then("I should see \"maxlength=\\\"100\\\"\"");
#line 107
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table10.AddRow(new string[] {
                        "Fields[0].InputFieldSettings.Required",
                        "true"});
#line 108
  testRunner.And("I fill in", ((string)(null)), table10);
#line 111
  testRunner.And("I hit \"Save\"");
#line 112
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table11.AddRow(new string[] {
                        "Event.Contact.Value",
                        ""});
#line 113
  testRunner.And("I fill in", ((string)(null)), table11);
#line 116
  testRunner.And("I hit \"Save\"");
#line 117
 testRunner.Then("I should see \"The field Contact is mandatory.\"");
#line 120
 testRunner.When("I go to \"Admin/Contents/Create/Event\"");
#line 121
 testRunner.Then("I should see \"Contact\"");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table12.AddRow(new string[] {
                        "Event.Contact.Value",
                        "contact@orchardproject.net"});
#line 122
 testRunner.When("I fill in", ((string)(null)), table12);
#line 125
  testRunner.And("I hit \"Save\"");
#line 126
  testRunner.And("I am redirected");
#line 127
 testRunner.Then("I should see \"Your Event has been created.\"");
#line 128
 testRunner.When("I go to \"Admin/Contents/List\"");
#line 129
 testRunner.Then("I should see \"Contact:\"");
#line 130
  testRunner.And("I should see \"contact@orchardproject.net\"");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
