// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Orchard.Fields.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Media Picker Field")]
    public partial class MediaPickerFieldFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Media.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Media Picker Field", "  In order to add a media content to my types\r\nAs an administrator\r\n  I want to c" +
                    "reate, edit and publish media fields", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating and using media fields")]
        public virtual void CreatingAndUsingMediaFields()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating and using media fields", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 9
    testRunner.Given("I have installed Orchard");
#line 10
  testRunner.And("I have installed \"Orchard.Fields\"");
#line 11
    testRunner.When("I go to \"Admin/ContentTypes\"");
#line 12
    testRunner.Then("I should see \"<a[^>]*>.*?Create new type</a>\"");
#line 13
    testRunner.When("I go to \"Admin/ContentTypes/Create\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table1.AddRow(new string[] {
                        "DisplayName",
                        "Event"});
            table1.AddRow(new string[] {
                        "Name",
                        "Event"});
#line 14
        testRunner.And("I fill in", ((string)(null)), table1);
#line 18
        testRunner.And("I hit \"Create\"");
#line 19
        testRunner.And("I go to \"Admin/ContentTypes/\"");
#line 20
    testRunner.Then("I should see \"Event\"");
#line 23
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line 24
  testRunner.And("I follow \"Add Field\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table2.AddRow(new string[] {
                        "DisplayName",
                        "File"});
            table2.AddRow(new string[] {
                        "Name",
                        "File"});
            table2.AddRow(new string[] {
                        "FieldTypeName",
                        "MediaPickerField"});
#line 25
  testRunner.And("I fill in", ((string)(null)), table2);
#line 30
  testRunner.And("I hit \"Save\"");
#line 31
  testRunner.And("I am redirected");
#line 32
 testRunner.Then("I should see \"The \\\"File\\\" field has been added.\"");
#line 35
 testRunner.When("I go to \"Admin/Contents/Create/Event\"");
#line 36
 testRunner.Then("I should see \"File\"");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table3.AddRow(new string[] {
                        "Event.File.Url",
                        ""});
#line 37
 testRunner.When("I fill in", ((string)(null)), table3);
#line 40
  testRunner.And("I hit \"Save\"");
#line 41
  testRunner.And("I am redirected");
#line 42
 testRunner.Then("I should see \"Your Event has been created.\"");
#line 43
 testRunner.When("I go to \"Admin/Contents/List\"");
#line 44
 testRunner.Then("I should see \"File:\"");
#line 45
  testRunner.And("I should see \"\"");
#line 48
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table4.AddRow(new string[] {
                        "Fields[0].MediaPickerFieldSettings.Hint",
                        "Please select a file"});
#line 49
  testRunner.And("I fill in", ((string)(null)), table4);
#line 52
  testRunner.And("I hit \"Save\"");
#line 53
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line 54
 testRunner.Then("I should see \"Please select a file\"");
#line 57
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table5.AddRow(new string[] {
                        "Fields[0].MediaPickerFieldSettings.Required",
                        "true"});
#line 58
  testRunner.And("I fill in", ((string)(null)), table5);
#line 61
  testRunner.And("I hit \"Save\"");
#line 62
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table6.AddRow(new string[] {
                        "Event.File.Url",
                        ""});
#line 63
  testRunner.And("I fill in", ((string)(null)), table6);
#line 66
  testRunner.And("I hit \"Save\"");
#line 67
 testRunner.Then("I should see \"The field File is mandatory.\"");
#line 70
 testRunner.When("I go to \"Admin/ContentTypes/Edit/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table7.AddRow(new string[] {
                        "ext-Fields[0].MediaPickerFieldSettings",
                        "true"});
            table7.AddRow(new string[] {
                        "Fields[0].MediaPickerFieldSettings.AllowedExtensions",
                        "jpg"});
#line 71
  testRunner.And("I fill in", ((string)(null)), table7);
#line 75
  testRunner.And("I hit \"Save\"");
#line 76
  testRunner.And("I go to \"Admin/Contents/Create/Event\"");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "name",
                        "value"});
            table8.AddRow(new string[] {
                        "Event.File.Url",
                        "~/Media/Default/images/Image.png"});
#line 77
 testRunner.And("I fill in", ((string)(null)), table8);
#line 80
  testRunner.And("I hit \"Save\"");
#line 81
 testRunner.Then("I should see \"The field File must be have one of these extensions: jpg\"");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
